name: Release_notes

on:
  push:
    tags: '*'
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: get_packets
        run: sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: generate_PDFs
        run: |
          cd ${{ github.workspace }}
          pandoc README.md -o test.pdf
          ls
      
      